variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  key: "$CI_JOB_NAME"
  paths:
    - .cache/pip

stages:
  - Static Analysis
  - Test
default:
  before_script:
    - pip install -U pip setuptools wheel
    - python -V
lint:
  stage: Static Analysis
  image: python:3.7
  script:
    - pip install tox
    - tox -e lint
pytest:
  stage: Test
  image: python:3.7
  coverage: '/^TOTAL.+?(\d+\%)$/'
  script:
    - apt-get update && apt-get install -y libgl1-mesa-dev # Fix cv2 error: https://stackoverflow.com/q/63977422/2804645
    - pip install -r requirements.txt
    - pip install -r requirements-interactive.txt
    - pip install ".[interactive]"
    - pip install -U pytest pytest-cov
    - pytest --color=yes --junitxml=report.xml
  # See here for JUnit test reports
  # https://docs.gitlab.com/ee/ci/unit_test_reports.html#python-example
  artifacts:
    when: always
    reports:
      junit: report.xml
