version: "3.5"
services:

  atlannot:
    build:
      context: .
      dockerfile: docker/atlannot.Dockerfile
      args:
        - BBP_HTTP_PROXY
        - BBP_HTTPS_PROXY
        - BBP_USERS
    image: atlannot
    container_name: atlannot
